### ISSUE TITLE
OOM with recursive map value

### ISSUE THREAD

**Issue by nitsky** [tangramdotdev/tangram#203]
```
export default tg.target(async () => {
  let x = {};
  x.x = x;
  return x;
});
```

**Comment by endbr64** [comment]
At first we thought that the overflow needs to be detected in [`impl FromV8 for BTreeMap`](https://github.com/tangramdotdev/tangram/blob/945f67870a4e3549db567ad6beed014bd6d5653f/packages/v8/src/convert.rs#L678), but I don't think we ever reach that stage. I think the infinite recursion actually occurs during the call to [`promise_resolver.resolve()`](https://github.com/tangramdotdev/tangram/blob/945f67870a4e3549db567ad6beed014bd6d5653f/packages/server/src/runtime/js.rs#L275), which happens entirely in V8. I could be wrong, since I don't fully understand the control flow here.
