### ISSUE TITLE
Unable to install tangram python library

### ISSUE THREAD

**Issue by DannyBen** [tangramdotdev/tangram#22]
On Ubuntu 18

```
$ pip3 install tangram
Collecting tangram
  Could not find a version that satisfies the requirement tangram (from versions: )
No matching distribution found for tangram

$ pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
```

This is reproducible on two different systems (although similar OS and specs).

**Comment by nitsky** [comment]
Hi @DannyBen, after looking into this I have discovered that tangram requires pip >= 20.3, because it requires a version of pip that supports [PEP 600](https://www.python.org/dev/peps/pep-0600/) to install its native extension. It may be possible to support pip >= 19.3 with some changes in the future, but it will never be possible for us to support pip >= 9.0.1.

You can get tangram installed by upgrading pip. On Ubuntu 18.04 I was able to do so just by running:

```
pip3 install --upgrade pip
``` 

However, a better solution is to use a virtual environment:

```
apt install -y python3 python3-venv
python3 -m venv .venv
source .venv/bin/activate
pip3 install --upgrade pip
```

Either way, just confirm that pip is now at version 20.3 or later, and tangram should install correctly.

I have added a note to the README for the python package explaining this [here](https://github.com/tangramdotdev/tangram/commit/fcccd1365e3aef8bddfcffa9a8d6dc10299ce395).

**Comment by DannyBen** [comment]
Excellent, thanks for the update.

I can confirm upgrading pip solved it.
I had no idea my pip3 is so outdated - I am only using it to install third party stuff, not for day to day python development.

I guess I can close this right? If not, reopen as you see fit.
