### ISSUE TITLE
format fails on packages with non-module path dependencies

### ISSUE THREAD

**Issue by deciduously** [tangramdotdev/tangram#296]
The CLI `format` command fails with this error on packages which import artifacts that are not modules:
```
-> Not a directory (os error 20)
-> failed to check if file exists
   internal:packages/server/src/package/format.rs:64:15 tangram_server::package::format::<impl tangram_server::Server>::format_module::{{closure}}::{{closure}}
   path = /Users/benlovy/code/packages/packages/attr/tangram.ts/patches
```

The offending import:
```
import patches from "./patches" with { type: "directory" };
```
It tried creating the invalid path `/Users/benlovy/code/packages/packages/attr/tangram.ts/patches`, which fails at the `try_exists()` call because the parent is not a directory.

**Comment by endbr64** [comment]
I did the simplest fix possible [here](https://github.com/tangramdotdev/tangram/commit/cd925128937d679902ad1c1906906ea48d6f7df3), and I doubt that it's right. What is the expected behavior?

I'm also adding tests [here](https://github.com/tangramdotdev/tangram/blob/d4c5a5debd6c340dbd54dae40ed9b233af4d5858/packages/server/src/package/tests.rs) and would appreciate more ideas.
